name: David J Anderson Jr
favicon: null
layout_spectrum: 0.16276009078137577
typography_spectrum: 0.45024945330806077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5628943413030356
  lightness: 0.391875131521374
  saturation: 0.24291341891512275
  rhythmicContrast: 0.14857712015509605
purpose: []
